-- CREATE TABLE User (
--     user_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
--     name VARCHAR(100) NOT NULL,
--     email VARCHAR(100) NOT NULL UNIQUE,
--     password VARCHAR(100) NOT NULL,
--     is_staff BOOLEAN DEFAULT FALSE
-- );

INSERT INTO User (user_ID, name, email, password, is_staff) VALUES
(11, 'Alice Smith', 'alice.smith@example.com', 'password1', FALSE),
(12, 'Bob Johnson', 'bob.johnson@example.com', 'password2', FALSE),
(13, 'Charlie Brown', 'charlie.brown@example.com', 'password3', FALSE),
(14, 'David Wilson', 'david.wilson@example.com', 'password4', FALSE),
(15, 'Eve Davis', 'eve.davis@example.com', 'password5', FALSE),
(16, 'Frank Miller', 'frank.miller@example.com', 'password6', FALSE),
(17, 'Grace Lee', 'grace.lee@example.com', 'password7', FALSE),
(18, 'Henry Walker', 'henry.walker@example.com', 'password8', FALSE),
(19, 'Ivy Hall', 'ivy.hall@example.com', 'password9', FALSE),
(20, 'Jack Young', 'jack.young@example.com', 'password10', FALSE),
(21, 'Karen Allen', 'karen.allen@example.com', 'password11', FALSE),
(22, 'Larry Scott', 'larry.scott@example.com', 'password12', FALSE),
(23, 'Megan King', 'megan.king@example.com', 'password13', FALSE),
(24, 'Nathan Wright', 'nathan.wright@example.com', 'password14', FALSE),
(25, 'Olivia Green', 'olivia.green@example.com', 'password15', FALSE),
(26, 'Paul Baker', 'paul.baker@example.com', 'password16', FALSE),
(27, 'Quinn Adams', 'quinn.adams@example.com', 'password17', FALSE),
(28, 'Rachel Nelson', 'rachel.nelson@example.com', 'password18', FALSE),
(29, 'Sam Carter', 'sam.carter@example.com', 'password19', FALSE),
(30, 'Tina Mitchell', 'tina.mitchell@example.com', 'password20', FALSE),
(31, 'Uma Perez', 'uma.perez@example.com', 'password21', FALSE),
(32, 'Victor Roberts', 'victor.roberts@example.com', 'password22', FALSE),
(33, 'Wendy Evans', 'wendy.evans@example.com', 'password23', FALSE),
(34, 'Xander Hughes', 'xander.hughes@example.com', 'password24', FALSE),
(35, 'Yara Simmons', 'yara.simmons@example.com', 'password25', FALSE),
(36, 'Zack Foster', 'zack.foster@example.com', 'password26', FALSE),
(37, 'Abby Morgan', 'abby.morgan@example.com', 'password27', FALSE),
(38, 'Ben Reed', 'ben.reed@example.com', 'password28', FALSE),
(39, 'Cindy Bell', 'cindy.bell@example.com', 'password29', FALSE),
(40, 'Derek Cox', 'derek.cox@example.com', 'password30', FALSE),
(41, 'Ella Ward', 'ella.ward@example.com', 'password31', FALSE),
(42, 'Finn Gray', 'finn.gray@example.com', 'password32', FALSE),
(43, 'Gina Brooks', 'gina.brooks@example.com', 'password33', FALSE),
(44, 'Hank Powell', 'hank.powell@example.com', 'password34', FALSE),
(45, 'Isla Long', 'isla.long@example.com', 'password35', FALSE),
(46, 'Jake Patterson', 'jake.patterson@example.com', 'password36', FALSE),
(47, 'Kylie Ross', 'kylie.ross@example.com', 'password37', FALSE),
(48, 'Liam Price', 'liam.price@example.com', 'password38', FALSE),
(49, 'Mia Sanders', 'mia.sanders@example.com', 'password39', FALSE),
(50, 'Noah Barnes', 'noah.barnes@example.com', 'password40', FALSE),
(51, 'Olga Hayes', 'olga.hayes@example.com', 'password41', FALSE),
(52, 'Pete Coleman', 'pete.coleman@example.com', 'password42', FALSE),
(53, 'Quincy Jenkins', 'quincy.jenkins@example.com', 'password43', FALSE),
(54, 'Rita Kelly', 'rita.kelly@example.com', 'password44', FALSE),
(55, 'Steve Howard', 'steve.howard@example.com', 'password45', FALSE),
(56, 'Tara Bryant', 'tara.bryant@example.com', 'password46', FALSE),
(57, 'Umar Ortiz', 'umar.ortiz@example.com', 'password47', FALSE),
(58, 'Vera Butler', 'vera.butler@example.com', 'password48', FALSE),
(59, 'Will Sanders', 'will.sanders@example.com', 'password49', FALSE),
(60, 'Xena Flores', 'xena.flores@example.com', 'password50', FALSE);
